version: "3.9"
services:
  jellyfin:
    image: ghcr.io/aleksasiriski/jellyfin-rffmpeg-server:latest
    environment:
      - TZ=Europe/Berlin
#      - JELLYFIN_PublishedServerUrl=https://jellyfin.example.com
    ports:
      - ${SERVER_LAN_IP:-}:8096:8096
    volumes:
      - jellyfin-conf:/config:z
      - jellyfin-cache:/cache:z
      - /var/storage/media:/var/storage/media:ro
    restart: always
  nfs-server:
    image: docker.io/itsthenetwork/nfs-server-alpine:latest
    cap_add:
      - SYS_ADMIN
    environment:
      - TZ=Europe/Berlin
      - NFS_EXPORT_0="/var/jellyfin/config *(rw,sync,no_subtree_check,no_root_squash)"
      - NFS_EXPORT_1="/var/jellyfin/cache *(rw,sync,no_subtree_check,no_root_squash)"
    ports:
      - ${NFS_LAN_IP:-}:2049:2049
    volumes:
      - jellyfin-conf:/var/jellyfin/config:z
      - jellyfin-cache:/var/jellyfin/cache:z
    restart: always
volumes:
  jellyfin-conf:
  jellyfin-cache:
